name: Build

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-php-82:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: ./.github/actions/test
        with:
          php_version: '82'

  test-php-83:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: ./.github/actions/test
        with:
          php_version: '83'
