name: Build

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  test-php-82:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Checkout repository
        uses: ./.github/actions/test
        with:
          php_version: '82'

  test-php-83:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Checkout repository
        uses: ./.github/actions/test
        with:
          php_version: '83'

  test-php-84:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Checkout repository
        uses: ./.github/actions/test
        with:
          php_version: '84'

  test-php-85:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Checkout repository
        uses: ./.github/actions/test
        with:
          php_version: '85'

