name: Build

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-php-82:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and test for PHP 8.2
        run: |
          make up daemon=1 php_version=82
          docker ps -a
          docker network ls
          make copy php_version=82
          make build php_version=82 container_mode=1
          make test php_version=82 container_mode=1
          make down php_version=82

  test-php-83:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and test for PHP 8.3
        run: |
          make up daemon=1 php_version=83
          docker ps -a
          docker network ls
          make copy php_version=83
          make build php_version=83 container_mode=1
          make test php_version=83 container_mode=1
          make down php_version=83
